import images from 'constants/images';
const BiometryTypes = {
  Face: 'Face', // Android
  FaceID: 'FaceID',
  Fingerprint: 'Fingerprint', // Android
  none: 'none',
  passcode: 'passcode',
  TouchID: 'TouchID',
};
const userInitialState = {
  wallet: {
    balance: 0,
    transactions: [],
    trades: [],
    banks: [],
  },
  avatar: '',
  notifications: [],
  BVN: '',
  role: 'user',
  suspended: false,
  userId: '',
  _id: '',
  name: '',
  email: '',
  phoneNumber: '',
  lastLogin: '',
  createdAt: '',
  updatedAt: '',
  accessToken: '',
  refreshToken: '',
  username: '',
};

export default {
  BiometryTypes,
  userInitialState,
  giftCards: [
    {title: 'Amazon', displayName: 'Amazon'},
    {title: 'American exp', displayName: 'American Express'},
    {title: 'Applestore', displayName: 'Apple Store'},
    {title: 'colorpop', displayName: 'colorpop'},
    {title: 'ebay', displayName: 'ebay'},
    {title: 'itunes', displayName: 'itunes'},
    {title: 'JCPenny', displayName: 'JCPenny'},
    {title: 'macy', displayName: 'macy'},
    {title: 'nike', displayName: 'nike'},
    {title: 'offgamers', displayName: 'offgamers'},
    {title: 'Playstation', displayName: 'Playstation'},
    {title: 'steam', displayName: 'steam'},
    {title: 'Bestbuy', displayName: 'Bestbuy'},
    {title: 'sakes', displayName: 'sakes'},
    {title: 'google play', displayName: 'Google Play'},
    {title: 'razer', displayName: 'razer'},
    {title: 'sephora', displayName: 'sephora'},
    {title: 'Target', displayName: 'Target'},
    {title: 'Vanilla', displayName: 'Vanilla'},
    {title: 'visa', displayName: 'visa'},
  ],
  cardSub: {
    label: 'Select Sub-Category',
    value: 'Select Card Sub Category',
  },
  cardsubcategory: [
    {label: 'Choose Card Category', value: '1'},
    {label: 'Choose Card Category', value: '2'},
    {label: 'Choose Card Category', value: '3'},
  ],
  addBankPlaceholder: {
    label: 'Choose Bank',
    value: 'Choose Bank',
  },
  cardCategory: {
    label: 'Choose Gift Card',
    value: 'Choose Gift Card',
  },
  banks: [
    {label: 'Abbey Mortgage Bank', value: '801'},
    {label: 'Access Bank', value: '044'},
    {label: 'Access Bank (Diamond)', value: '063'},
    {label: 'ALAT by WEMA', value: '035A'},
    {label: 'ASO Savings and Loans', value: '401'},
    {label: 'Bowen Microfinance Bank', value: '50931'},
    {label: 'CEMCS Microfinance Bank', value: '50823'},
    {label: 'Citibank Nigeria', value: '023'},
    {label: 'Coronation Merchant Bank', value: '559'},
    {label: 'Ecobank Nigeria', value: '050'},
    {label: 'Ekondo Microfinance Bank', value: '562'},
    {label: 'Eyowo', value: '50126'},
    {label: 'Fidelity Bank', value: '070'},
    {label: 'First Bank of Nigeria', value: '011'},
    {label: 'First City Monument Bank', value: '214'},
    {label: 'FSDH Merchant Bank Limited', value: '501'},
    {label: 'Globus Bank', value: '00103'},
    {label: 'Guaranty Trust Bank', value: '058'},
    {label: 'Hackman Microfinance Bank', value: '51251'},
    {label: 'Hasal Microfinance Bank', value: '50383'},
    {label: 'Heritage Bank', value: '030'},
    {label: 'Ibile Microfinance Bank', value: '51244'},
    {label: 'Infinity MFB', value: '50457'},
    {label: 'Jaiz Bank', value: '301'},
    {label: 'Keystone Bank', value: '082'},
    {label: 'Kuda Bank', value: '50211'},
    {label: 'Lagos Building Investment Company Plc.', value: '90052'},
    {label: 'Mayfair MFB', value: '50563'},
    {label: 'One Finance', value: '565'},
    {label: 'PalmPay', value: '999991'},
    {label: 'Parallex Bank', value: '526'},
    {label: 'Parkway - ReadyCash', value: '311'},
    {label: 'Paycom', value: '999992'},
    {label: 'Petra Mircofinance Bank Plc', value: '50746'},
    {label: 'Polaris Bank', value: '076'},
    {label: 'Providus Bank', value: '101'},
    {label: 'Rand Merchant Bank', value: '502'},
    {label: 'Rubies MFB', value: '125'},
    {label: 'Sparkle Microfinance Bank', value: '51310'},
    {label: 'Stanbic IBTC Bank', value: '221'},
    {label: 'Standard Chartered Bank', value: '068'},
    {label: 'Sterling Bank', value: '232'},
    {label: 'Suntrust Bank', value: '100'},
    {label: 'TAJ Bank', value: '302'},
    {label: 'TCF MFB', value: '51211'},
    {label: 'Titan Bank', value: '102'},
    {label: 'Union Bank of Nigeria', value: '032'},
    {label: 'United Bank For Africa', value: '033'},
    {label: 'Unity Bank', value: '215'},
    {label: 'VFD Microfinance Bank Limited', value: '566'},
    {label: 'Wema Bank', value: '035'},
    {label: 'Zenith Bank', value: '057'},
  ],
};
