require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Nosh' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'NoshTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  
  pod 'OpenSSL-Universal', '~>1.0.2.20'
end

target 'Nosh-tvOS' do
  # Pods for Nosh-tvOS

  target 'Nosh-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
